<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>flow</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Flow</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|switch|default|native|import|forbid|export|unittest)\b</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\%[^%]*(\b(if|else|endif)\b)[^%]*\%</string>					
					<key>captures</key>
				    <dict>
						<key>0</key>
				        <dict>
				            <key>name</key>
				            <string>constant.character.escape.untitled</string>					
				        </dict>
				        <key>1</key>
				        <dict>
				            <key>name</key>
				            <string>keyword.control.untitled</string>
				        </dict>
				    </dict>
				</dict>
				<dict>
					<key>match</key>
					<string>%([^%]*)%</string>		
					<key>name</key>
				    <string>constant.character.escape.untitled</string>						
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(\b(bool|double|int|void|string|io|ref|flow|mutable)\b)|\?|\{|\}</string>
			<key>name</key>
			<string>storage.type.flow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>==|!=|&lt;=|&gt;=|&lt;|&gt;</string>
			<key>name</key>
			<string>keyword.operator.comparison.flow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;&amp;|\!|\|\||</string>
			<key>name</key>
			<string>keyword.operator.logical.flow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|\:=|\:\:=</string>
			<key>name</key>
			<string>keyword.operator.assignment.flow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\-&gt;</string>
			<key>name</key>
			<string>keyword.operator.arrow.flow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\|&gt;</string>
			<key>name</key>
			<string>keyword.operator.pipe.flow</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\+|\*|\-|\%|\:|/|\'|\\|\|\||\|\.|\^</string>
			<key>name</key>
			<string>keyword.operator.flow</string>
		</dict>


		<dict>
			<key>match</key>
			<string>;|\[|\]|\{|\}</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>

		<dict>
			<key>match</key>
			<string>^(\w+\W*)\s*(\(|=)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.js</string>
				</dict>
			</dict>
		</dict>


	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.flow</string>
						</dict>
					</dict>
					<key>match</key>
					<string>/\*\*/</string>
					<key>name</key>
					<string>comment.block.empty.flow</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
			</array>
		</dict>
		<key>comments-inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.flow</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.flow</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.flow</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.flow</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*((//).*$\n?)</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.flow</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.flow</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.flow</string>
	<key>uuid</key>
	<string>82D8B721-3D72-4D0C-948C-30B7232BF8B8</string>
</dict>
</plist>
