{
	"working_dir": "${project_path:${folder}}",
	"cmd": ["compile.sh", "$file_name", "$project_path"],
	"file_regex": "(?<file>.*\\.flow):(?<line>[0-9]*):",
	"path": "/Users/dmitrys/Devel/haxe:/Users/dmitrys/Devel/neko:/Users/dmitrys/Devel/Area9.dk/flow2/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
	"env": {
		"DYLD_LIBRARY_PATH": "/Users/dmitrys/Devel/neko"
	}
}
