#!/bin/sh

# Update origin first of all
git fetch

# See if there are unsynced commits between master and origin/master
LOG=$(git log ..origin/master)

# Now show the same changes, but nicely
git log --format="%n%n--- %h by %Cgreen%aN%Creset, %ar --- %n%C(yellow)%s%Creset%n%b" --no-merges --stat ..origin/master

if [ "$LOG" = "" ]; then
    echo No new changes.
else
    read -n1 -p "Do you want to merge the changes above to your working folder? (Y/N)" yn
    case $yn in
        [Yy]* ) printf "\n"; git merge origin master & git rebase;;
        [Nn]* ) exit;;
    esac
fi