
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#if !defined (__RSVG_RSVG_H_INSIDE__) && !defined (RSVG_COMPILATION)
#warning "Including <librsvg/librsvg-enum-types.h> directly is deprecated."
#endif

#ifndef __LIBRSVG_ENUM_TYPES_H__
#define __LIBRSVG_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
 /* enumerations from "rsvg.h" */
GType rsvg_error_get_type (void);
#define RSVG_TYPE_ERROR (rsvg_error_get_type())
GType rsvg_handle_flags_get_type (void);
#define RSVG_TYPE_HANDLE_FLAGS (rsvg_handle_flags_get_type())
G_END_DECLS

#endif /* __LIBRSVG_ENUM_TYPES_H__ */

/* Generated data ends here */

