convert index.markdown index.html
convert flow.markdown flow.html
convert form.markdown form.html
convert runtimes.markdown runtimes.html
convert development.markdown development.html
convert lingo.markdown lingo.html
convert windows.markdown windows.html
convert mac.markdown mac.html
convert linux.markdown linux.html
convert tropic.markdown tropic.html
convert faq.markdown faq.html
