# REQUIRES DOCKER >= 17.05 for multi-stage builds
# Makes resulting image smaller.

# FROM does not understand ARG, so being awkward here
FROM area9/qt:%QT_VERSION%-install as qt

FROM alpine

ARG qt_version=5.9.2
ARG qt_path=/opt/Qt${qt_version}
ARG qt_full_path=${qt_path}/${qt_version}/gcc_64

COPY --from=qt ${qt_full_path} ${qt_full_path}

