<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>math</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Math</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(BEGIN|END|cases|for)\b</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(\bQUOTE\b|\$)</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
	
		<dict>
			<key>match</key>
			<string>\+|\*|\-|\!|\%|\:|/|\:=|=|\'|,|\\|!=|&lt;=|&gt;=|&lt;|&gt;|&amp;&amp;|\|\||\:\:=|\|&gt;|-&gt;|\.|\^</string>
			<key>name</key>
			<string>keyword.operator.js</string>
		</dict>

		<dict>
			<key>match</key>
			<string>;|\[|\]|\{|\}</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>

		<dict>
			<key>match</key>
			<string>([a-z]|[A-Z]+|#[a-zA-Z]+)(\([^)]*\))?+\s*:=</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.js</string>
				</dict>
			</dict>
		</dict>

		<dict>
			<key>match</key>
			<string>([a-z]|[A-Z]+|#[a-zA-Z]+)</string>
			<key>name</key>
			<string>support.constant.js</string>
		</dict>

<!--
	<dict>
		<key>match</key>
		<string>([a-z]|[A-Z]+|#[a-zA-Z]+)</string>
		<key>def</key>
		<string>constant.language.js</string>
	</dict>

	constant.language.js
		<dict>
			<key>match</key>
			<string>([a-z]|[A-Z]+|#[a-zA-Z]+)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.js</string>
				</dict>
			</dict>
		</dict>
-->

	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.math</string>
						</dict>
					</dict>
					<key>match</key>
					<string>/\*\*/</string>
					<key>name</key>
					<string>comment.block.empty.math</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments-inline</string>
				</dict>
			</array>
		</dict>
		<key>comments-inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.math</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.math</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.math</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.math</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*((//).*$\n?)</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.math</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
					<key>name</key>
					<string>constant.numeric.math</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.math</string>
	<key>uuid</key>
	<string>82D8B721-3D72-4D0C-948C-30B7232BF8B8</string>
</dict>
</plist>
